slug = "yeehaw"
title = "Yeehaw"
author = "Jerry"
value = 15
description = """Will you be the [yee](happy.jpeg) to my [haw](sad.jpeg)? Hint: https://hexed.it/ might be something interesting to look into."""
tags = [ "forensics" ]
files = ["happy.jpeg", "sad.jpeg"]
flag = "flag{i_want_to_be_a_cowboy_baby}"
enabled = true 