slug = "booking-it"
title = "Booking It"
author = "Salma"
value = 10
description = """I just received this [message](message.txt) from my good friend, Mr. S.I. Furr, a world-renowned author, containing a strange sequence of numbers. Seems like he was being chased by his many fans and had to book it before he could tell me how to interpret them. Looks like they were wondering when he'd be updating ACM Cyber's [website](https://acmcyber.com/).  Can you help me figure out what those numbers mean? (Note: enter the flag as flag{FLAG} with the flag in caps. No spaces between words)"""
tags = [ "crypto"]
files = ["message.txt"]
flag = "flag{BOOKCIPHERISBESTCIPHER}"
enabled = true 