slug = "bounty-hunter"
title = "Bounty Hunter"
author = "Laura"
value = 15
description = """A bounty hunter delivered this message to me after I claimed the bounty for a famous outlaw that he... may or may not have killed. Must be the first time he's ever been crossed... certainly seems like quite the character. Can you help me decode [this](threat.txt) message? (Format as flag{word1_word2_word3}. All lowercase)"""
tags = [ "cryptography" ]
files = [ "threat.txt" ]
flag = "flag{duel_at_dawn}"
enabled = true 