slug = "serious-leak"
title = "Serious Leak"
author = "Rory"
value = 30
description = """What are the chances? We just happened to intercept a message containing detailed [specifications](message.txt) for a new internet protocol addressed to the one and only JOE BRUIN. Unfortunately they are encrypted so I don't think we'll ever be able to read them. In **Completely** unrelated news someone just hacked Joe Bruins machine, and leaked their entire [filesystem](filesystem.zip). Its alright though, I'm sure it didn't contain any sensitive information."""
tags = ["crypto", "forensics"]
flag = "flag{remember_kids__dont_lose_your_keys}"
files = ["message.txt", "filesystem.zip"]
enabled = true
