slug = "law-and-xorder"
title = "Law and Xorder"
author = "Salma"
value = 15
description = """The sheriff is on his way to deliver divine punishment. He has sent you [two](he_approaches.png) [images](oh_god_hes_coming.png) as advance warning of his arrival. Maybe if you compare the two, you can find some hidden message that will prevent him from carrying out his twisted form of judgement. (Hint: take a good look at the challenge title to figure out how to compare the two images)"""
tags = [ "stego"]
files = ["he_approaches.png", "oh_god_hes_coming.png"]
flag = "flag{h3r3_c0m3s_th3_sh3r1ff}"
enabled = true 